### ISSUE TITLE
Program only by soldering ?

### ISSUE THREAD

**Issue by vincegre** [jorgecis/Remotsy#1]
Hi

Isn't it possible to use the TX/RX/GND pin available on corner of board to flash the ESP ? No other solution than to solder wire directly on ESP ?
Would be nice to be able to flash it with some easy pins or through the USB (would need to add an uart for that last option I guess ?)

Vincèn

**Comment by jorgecis** [comment]
Hi,

  Why do you say that is impossible to use the TX/RX/GND? Using a USB-TTL cable is very easy to use those pins, (Don't use the red power cable) 
<img width="450" alt="board connected via TTL" src="https://user-images.githubusercontent.com/5554042/42071891-73e25fa8-7b23-11e8-88a3-b7a1c16a7b41.png">

  I used the pins to flash every board that I sold, is a very simple process and I did it without soldering anything.

   And yes the board doesn't have any uart, so is impossible to flash it using the USB port, When I created the board, I didn't add the uart and the other parts do not increase the cost. And my main goal was to use it with my firmware and my cloud server and also I made easy to flash the board.
   

Check this video https://youtu.be/0FxteE6comw

**Comment by vincegre** [comment]
> Why do you say that is impossible to use the TX/RX/GND? Using a USB-TTL cable is very easy to use those pins, (Don't use the red power cable)

I never said it was impossible, I was asking if it was possible to use these pins to flash it ;) 

> Check this video https://youtu.be/0FxteE6comw

Thanks for video link but It's pretty useless !! It would be nice to show exactly which pins to shortcut on ESP to put it in Flash mode which is not clearly visible on video ! The push button on board is not linked to correct GPIO for Flash mode ?

**Comment by vincegre** [comment]
> Thanks for video link but It's pretty useless !! It would be nice to show exactly which pins to shortcut on ESP to put it in Flash mode which is not clearly visible on video ! The push button on board is not linked to correct GPIO for Flash mode ?

No answer ?

**Comment by vincegre** [comment]
??????

**Comment by gigawatts** [comment]
@jorgecis @vincegre I have [submitted a pull request](https://github.com/jorgecis/Remotsy/pull/3) with a corrected PCB image containing the correct pin 0 and ground pad locations.

**Comment by gigawatts** [comment]
@jorgecis Can you provide what Arduino board settings you used to flash the Remotsy? From your video, it looks like you used the "Adafruit Feather HUZZAH ESP8266" board type, but all of the other settings (Flash size, Debug port, debug level, IwIP Variant, VTables, CPU Freq, etc) would be helpful.

**Comment by gigawatts** [comment]
Small update, I was able to get this working in PlatformIO after noticing thats what your source code came from. I didn't previously know about PlatformIO, that is a pretty awesome IDE! I'm still curious what the correct settings are for the regular Arduino IDE, but I have at least gotten code to run from PlatformIO.

**Comment by jorgecis** [comment]
@gigawatts  Thanks for the pull request, the chip that I use in Remotsy is the ESP12E, in the video I used PlataformIO, and yes I used the setting for the Adafruit ESP8266. 

Now I'm using the setting for the board "esp12E", here is the plataform.ini content

> [env:huzzah]
> platform = espressif8266
> board = esp12E
> framework = arduino
> build_flags =  -DMQTT_MAX_PACKET_SIZE=512
> monitor_speed = 115200
> 
> lib_deps =
>   IRremoteESP8266
>   Adafruit NeoPixel

I'll get the information that you want and I'll add here.

**Comment by jorgecis** [comment]
@gigawatts Yes, PlataformIO is an awesome IDE!!  I don't remember when was the last time that I used the Arduino IDE, for that reason I don't remember the settings that you ask me. I'll install it again and give you the settings.
