### ISSUE TITLE
API documentation ??

### ISSUE THREAD

**Issue by vincegre** [jorgecis/Remotsy#2]
Found the API documentation on that page https://www.remotsy.com/static/help/api.htm but would you have more details to share about arguments to pass at API ? Encoding, syntax, description of each field ?

Thanks

Vincèn

**Comment by jorgecis** [comment]
Hi Vicen,

The API documentation is a little confused but is very simple, most of the functions are  POST calls, you need post json data and the return is json data.

 The first thing that you need to do, is getting the auth key,  do a json post  to /rest/session/login  with the data 
   `{
   "username": "string",
   "password": "string"
}`

Then use the auth string in the next calls, for example to get the list of controls do a POST to /rest/controls/list with the POST data

`{
   "auth_key": "string"
}`

Example:
`curl --data '{ "username": "_____@gmail.com", "password": "XXXX" }' https://remotsy.com/rest/session/login`

if the credentials are correct you will see something like this

`{"data": {"msg": "Login Success", "auth_key": "d78d096d91604b0d97a2b6f404b116d5"}, "status": "success"}`

Also I released a python library, [https://github.com/jorgecis/RemotsyLib](https://github.com/jorgecis/RemotsyLib)
And my friend released a Go lang library [https://github.com/jaytarang92/goremotsy](https://github.com/jaytarang92/goremotsy)

**Comment by vincegre** [comment]
Thanks Jorge for explanations and I better understand now ! Unhappy I misunderstood the way it works ! I thought the API call could be done on the Remotsy itself not Internet remotsy server !
So still stuck on how to use it with Home Assistant in an easy way :( Is there a way to get Remotsy send IR commands at demand from Home Assistant without needing internet connection ? Does the complete IR lib is loaded in Remotsy when you select a device on website or website just sends specific code to pulse at Remotsy device ? or get Remotsy pulse IR codes at RC5 format ?
My problem is still with discrete codes that you can't capture as they don't exist in realworld !

**Comment by jorgecis** [comment]
Sorry, but the firmware was designed to be cloud controlled, the IR database is on my server, the IR code is sent to the remotsy via MQTT. Using the API you can send any command or a RAW IR code.

Can you tell me what is your problem, You can use Remotsy to capture codes.

You can create your own firmware and flash remotsy, take a look at the infrared library [https://github.com/markszabo/IRremoteESP8266](https://github.com/markszabo/IRremoteESP8266)
There is an example there that you can use to send codes locally without internet.

I can help you with the problems creating your own firmware.

**Comment by vincegre** [comment]
Thanks @jorgecis for all the details ;)
My problem is this one: I agree that I can capture all IR codes I need with Remotsy to be able to send them back later. But the problem is discrete IR codes as these ones don't exist on a remote or I would need to use a Remotsy as emitter for these discreet codes and one as receiver to capture them but it's a little boring setup.
I use Esphomeyaml formware for my ESP and that firmware uses too the IRremoteESP8266 lib to emit/capture IR. Perhaps you could share the IR database so it can be used directly to emit the IR codes for the ones using alternative firmwares/not using cloud system. Would it be possible ? or make an open database so other users can contribute to it ;)

**Comment by vincegre** [comment]
> Thanks @jorgecis for all the details ;)
> My problem is this one: I agree that I can capture all IR codes I need with Remotsy to be able to send them back later. But the problem is discrete IR codes as these ones don't exist on a remote or I would need to use a Remotsy as emitter for these discreet codes and one as receiver to capture them but it's a little boring setup.
> I use Esphomeyaml formware for my ESP and that firmware uses too the IRremoteESP8266 lib to emit/capture IR. Perhaps you could share the IR database so it can be used directly to emit the IR codes for the ones using alternative firmwares/not using cloud system. Would it be possible ? or make an open database so other users can contribute to it ;)

No answer about this ? :(

Thanks

**Comment by vincegre** [comment]
Definitively dead project, sad as I wanted to use your product for IR control :(

**Comment by jorgecis** [comment]
Sorry, but I can't share my database, there are many web pages with IR codes, for example this one http://irdb.tk/. The IRremoteESP8266 can use codes in my formats, like pronto, raw or globalcache.
