### ISSUE TITLE
Alt 3D printed case

### ISSUE THREAD

**Issue by gigawatts** [jorgecis/Remotsy#4]
Do you have the STLs available for this case?

http://www.remotsy.com/img/remo2.jpg
https://www.geeky-gadgets.com/wp-content/uploads/2016/11/Remotsy-WiFi-Remote-Created-To-Control-Amazon-Alexa-1.jpg

I like the looks of this case much more.

**Comment by jorgecis** [comment]
Yes, I have the STL but it will not work with the current board, that design was for my first board that was more rectangular, I'm working in a new design [https://s3.amazonaws.com/remotsy/new_design.jpeg](https://s3.amazonaws.com/remotsy/new_design.jpeg)

**Comment by vincegre** [comment]
New board ? it's no more the rectangular one ? as ones I have are the rectangular ones so would be still interested in STL files ;)

**Comment by vincegre** [comment]
Hum looks like it's dead here :(

**Comment by jorgecis** [comment]
No, is not a new board, is just a new 3d printed case.  the new case will still use the same PCB design.

**Comment by vincegre** [comment]
> No, is not a new board, is just a new 3d printed case. the new case will still use the same PCB design.

Thanks for update, hope you can share that new design soon so we can pack clean our Remotsy boards :+1:
