### ISSUE TITLE
Stock firmware

### ISSUE THREAD

**Issue by gigawatts** [jorgecis/Remotsy#5]
Can you provide the stock firmware or the source for the stock firmware so that I can restore my Remotsy to stock features after playing with custom firmware?

**Comment by jorgecis** [comment]
I'll upload the stock firmware here. So you can flash it and push the last version via the Remotsy console.

**Comment by jorgecis** [comment]
I added code, that you can use it to flash the original firmware. There is an error in the OTA function that made impossible use OTA after flash it via serial. So, the solution is Flash the Remotsy via serial, press the reset button and let the OTA finish.
